# Generated by Django 3.2.18 on 2023-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_description_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagetitle',
            field=models.CharField(max_length=70, null=True, unique=True, verbose_name='Название изображения'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
